kind: pipeline
name: default
type: docker

steps:

  - name: build server
    image: umputun/baseimage:buildgo-latest
    commands:
      - cd backend/app
      - go build -mod=vendor
      - echo "build completed"

  - name: docker master
    image: plugins/docker
    settings:
      repo: umputun/remark42
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - DRONE=${DRONE}
        - DRONE_TAG=${DRONE_TAG}
        - DRONE_COMMIT=${DRONE_COMMIT}
        - DRONE_BRANCH=${DRONE_BRANCH}
      tags:
        - ${DRONE_COMMIT_BRANCH/\//-}
    when:
      branch: [master]
      event: push

  - name: docker tag
    image: plugins/docker
    settings:
      repo: umputun/remark42
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - DRONE=${DRONE}
        - DRONE_TAG=${DRONE_TAG}
        - DRONE_COMMIT=${DRONE_COMMIT}
      tags:
        - ${DRONE_TAG}
        - latest
    when:
      event: tag

  - name: docker branch
    image: plugins/docker
    settings:
      repo: umputun/remark42
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - DRONE=${DRONE}
        - DRONE_COMMIT=${DRONE_COMMIT}
        - DRONE_BRANCH=${DRONE_BRANCH}
      tags:
        - ${DRONE_COMMIT_BRANCH/\//-}
      dry_run: true
    when:
      branch:
        exclude: [master, release/*]
        event: push

  - name: artifacts tag
    image: plugins/docker
    settings:
      dockerfile: Dockerfile.artifacts
      build_args:
        - DRONE=${DRONE}
        - DRONE_TAG=${DRONE_TAG}
        - DRONE_COMMIT=${DRONE_COMMIT}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    when:
      event: tag

  - name: deploy
    image: docker.umputun.com/system/deploy-ci:master
    commands:
      - ssh umputun@remark42.com "cd /srv/remark && docker-compose pull"
      - ssh umputun@remark42.com "cd /srv/remark && docker-compose up -d"
    when:
      branch: master
      event: push

  - name: notify
    image: drillster/drone-email
    settings:
      host: smtp.mailgun.org
      username:
        from_secret: email_username
      password:
        from_secret: email_password
      from: drone@mg.umputun.dev
      recipients: [ sys@umputun.dev ]
    when:
      status: [ changed, failure ]
